language: python
python: "3.10"

install:
  - pip install .
  - pip install build

script:
  # - make test-unit
  - python -m build

deploy:
    provider: pypi
    username: $ARTIFACTORY_USERNAME
    password: $ARTIFACTORY_API_KEY
    # TODO: determine which repository should be used for sage package
    # server: "https://na.artifactory.swg-devops.com/artifactory/api/pypi/<TBD>"
    server: ""
    distributions: sdist bdist_wheel
    on:
        tags: true
        condition: "$TRAVIS_TAG =~ [0-9]+\\.[0-9]+\\.[0-9]+(-(beta|rc|alpha)\\.[0-9])?$"